# -*- coding: utf-8 -*-
"""M3PA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Eu8B8C5WqqsOpWxq8GOs7WQhD_DadTr
"""



# PalmerPenguinsM3.py
# Parrish Robinson
# 10/05/26
# Uses lists and formatted output to analyze Palmer Penguin statistics.

import math

# Species constants
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

# Species Constants representing the number of observations
NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

# List of species names
SPECIES_NAMES=[
    SP_CHINSTRAP,
    SP_GENTOO,
    SP_ADELIE
]

# List of Species counts
SPECIES_COUNTS=[
    NUM_CHINSTRAP,
    NUM_GENTOO,
    NUM_ADELIE
]

# Determining Number of Species
TOTAL_SPECIES=len(SPECIES_NAMES)

# Calculating the Total number of Species
TOTAL_PENGUINS=sum(SPECIES_COUNTS)

# Calculating the average number of penguins per species
AVERAGE_PENGUINS=TOTAL_PENGUINS/TOTAL_SPECIES

AVERAGE_PENGUINS_ROUNDED_UP=math.ceil(AVERAGE_PENGUINS)

# Using indexes calculate species percentages
CHINSTRAP_PERCENT=SPECIES_COUNTS[0]/TOTAL_PENGUINS*100
GENTOO_PERCENT=SPECIES_COUNTS[1]/TOTAL_PENGUINS*100
ADELIE_PERCENT=SPECIES_COUNTS[2]/TOTAL_PENGUINS*100

# Finding the most and lowest observations
LARGEST_COUNT=max(SPECIES_COUNTS)
SMALLEST_COUNT=min(SPECIES_COUNTS)

LARGEST_INDEX=SPECIES_COUNTS.index(LARGEST_COUNT)
SMALLEST_INDEX=SPECIES_COUNTS.index(SMALLEST_COUNT)

LARGEST_SPECIES=SPECIES_NAMES[LARGEST_INDEX]
SMALLEST_SPECIES=SPECIES_NAMES[SMALLEST_INDEX]

# output the species name with introductory text
print("Introducing the Palmer Penguins:")
print(f"\t {SP_CHINSTRAP}!")
print(f"\t  {SP_GENTOO}!")
print("and last but not least...")
print(f"\t {SP_ADELIE}!")
print()
# output with species statistics
print(f"There are a total of {TOTAL_SPECIES} penguin species in this dataset.")
print(f"There are a total of {TOTAL_PENGUINS} penguins in the dataset.")
print(f"The average number of penguins per species is "
f"{AVERAGE_PENGUINS:.1f}.")
print(f"The average number rounded up is {AVERAGE_PENGUINS_ROUNDED_UP} penguins.")

print()

print(f"{SPECIES_NAMES[0]}: {SPECIES_COUNTS[0]} "
f"({CHINSTRAP_PERCENT:.2f}%)")
print(f"{SPECIES_NAMES[1]}: {SPECIES_COUNTS[1]} "
f"({GENTOO_PERCENT:.2f}%)")
print(f"{SPECIES_NAMES[2]}: {SPECIES_COUNTS[2]} "
f"({ADELIE_PERCENT:.2f}%)")

print()

print(f"The species with the most observations is {LARGEST_SPECIES} with {LARGEST_COUNT} penguins.")
print(f"The species with the fewest observations is {SMALLEST_SPECIES} with {SMALLEST_COUNT} penguins.")